version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changeme123
      POSTGRES_DB: postgres
    volumes:
      - .volumes/postgres:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Migrate.Dockerfile
    container_name: sqlx-migrate
    depends_on:
      db:
        condition: service_healthy
    command: [ "/bin/sh", "-c", "
      until pg_isready -h db -p 5432 -U user -d postgres; do
        sleep 2;
      done;
      sqlx migrate run --source /migrate/todo/migrations --database-url postgres://user:changeme123@db:5432/todo;
      sqlx migrate run --source /migrate/bartender/migrations --database-url postgres://user:changeme123@db:5432/bartender;
    " ]

  bartender:
    build:
      context: .
      dockerfile: Bartender.Dockerfile
    container_name: bartender
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  todo:
    build:
      context: .
      dockerfile: Todo.Dockerfile
    container_name: todo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db_data:
    driver: local
