use axum::routing::{get, post};
use axum::Router;

pub mod login;
pub mod refresh;
pub mod register;
pub mod validate;

pub use register::register;
pub use login::login;
pub use refresh::refresh;
pub use validate::validate;

// Export paths generated by utoipa
pub use register::__path_register;
pub use login::__path_login;
pub use refresh::__path_refresh;
pub use validate::__path_validate;

pub fn router() -> Router {
    Router::new()
        .route("/register", post(register))
        .route("/login", post(login))
        .route("/refresh", post(refresh))
        .route("/validate", get(validate))
}
