app:
  host: localhost
  port: 3001
  jwt_secret: secret
  access_token_expiration: 3600    # 60 * 60
  refresh_token_expiration: 604800 # 60 * 60 * 24 * 7
database:
  host: localhost
  port: 5432
  username: user
  password: changeme123
  database: bartender
  max_open_cons: 10
  min_idle_cons: 2
  conn_max_lifetime:
    secs: 900
    nanos: 0
  connection_timeout:
    secs: 15
    nanos: 0
  idle_timeout:
    secs: 3600
    nanos: 0
