app:
  host: localhost
  port: 3001
database:
  host: localhost
  port: 5432
  username: user
  password: changeme123
  database: test
  max_open_cons: 10
  min_idle_cons: 2
  conn_max_lifetime:
    secs: 900
    nanos: 0
  connection_timeout:
    secs: 15
    nanos: 0
  idle_timeout:
    secs: 3600
    nanos: 0
