name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-timeout=30s --health-start-period=30s

    steps:
      - uses: actions/checkout@v3

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to be ready...";
            sleep 5;
          done

      - name: Setup additional databases
        env:
          PGPASSWORD: password
        run: |
          psql -h localhost -U postgres -d postgres -c "CREATE DATABASE todo;"
          psql -h localhost -U postgres -d postgres -c "CREATE DATABASE bartender;"

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      # Setup Rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install sqlx-cli
        run: |
          if ! command -v sqlx &> /dev/null
          then
              echo "sqlx-cli not found. Installing..."
              cargo install sqlx-cli
          else
              echo "sqlx-cli is already installed (from cache)."
          fi

      # Cache sqlx-cli installation
      - name: Cache sqlx-cli
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-sqlx-cli-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-sqlx-cli-

      - name: Apply SQL migrations for todo
        run: |
          DATABASE_URL=postgres://postgres:password@localhost:5432/todo sqlx migrate run --source todo/migrations

      - name: Apply SQL migrations for bartender
        run: |
          DATABASE_URL=postgres://postgres:password@localhost:5432/bartender sqlx migrate run --source bartender/migrations

      - name: Run Tests for todo
        run: |
          DATABASE_URL=postgres://postgres:password@localhost:5432/todo cargo test --no-default-features --verbose -p todo --bin todo

      - name: Run Tests for bartender
        run: |
          DATABASE_URL=postgres://postgres:password@localhost:5432/todo cargo test --no-default-features --verbose -p todo --bin todo

      - name: Run Tests for other crates
        run: cargo test -p models -p auth -p todo-cli

# TODO: tests for repository
